# Generated by Django 5.2.1 on 2025-09-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodos', '0001_initial'),
        ('pedidos', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(db_column='id_cobro', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='monto_cobro', decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(blank=True, db_column='moneda_cobro', default='ARS', max_length=20, null=True)),
                ('descuento', models.DecimalField(blank=True, db_column='descuento', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('recargo', models.DecimalField(blank=True, db_column='recargo', decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('id_metodo_cobro', models.ForeignKey(db_column='id_metodo_cobro', on_delete=django.db.models.deletion.CASCADE, to='metodos.metodocobro')),
                ('pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='cobro', to='pedidos.pedido')),
            ],
            options={
                'db_table': 'cobros',
            },
        ),
    ]
