# Generated by Django 5.2.1 on 2025-11-11 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(db_column='id_cobro', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('credito', 'Crédito'), ('mercadopago', 'Mercado Pago')], db_column='tipo_cobro', max_length=20)),
                ('monto', models.DecimalField(db_column='monto_cobro', decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(blank=True, db_column='moneda_cobro', default='ARS', max_length=20, null=True)),
                ('fecha', models.DateField(db_column='fecha_cobro')),
                ('banco', models.CharField(blank=True, db_column='banco_cobro', max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, db_column='referencia_cobro', max_length=100, null=True)),
                ('cuotas', models.IntegerField(blank=True, db_column='cuotas_cobro', null=True)),
                ('descuento', models.DecimalField(blank=True, db_column='descuento_cobro', decimal_places=2, max_digits=10, null=True)),
                ('recargo', models.DecimalField(blank=True, db_column='recargo_cobro', decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'db_table': 'cobros',
            },
        ),
    ]
