# Generated by Django 5.2.1 on 2025-09-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_alter_cobro_pedido'),
        ('pedidos', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='pedido',
            field=models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='cobro', to='pedidos.pedido'),
        ),
    ]
