# Generated by Django 5.2.1 on 2025-10-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0004_alter_cobro_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='descuento_porcentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cobro',
            name='recargo_porcentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
