# Generated by Django 5.2.1 on 2025-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_categoria', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion_categoria')),
            ],
        ),
    ]
