# Generated by Django 5.2.1 on 2025-06-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
