version: '3.8'

services:

  db_usuarios:
    image: mysql:8.0
    container_name: db_usuarios
    restart: always
    environment:
      MYSQL_DATABASE: usuarios_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - usuarios_data:/var/lib/mysql

  usuarios:
    build: ./backend/service_usuarios
    container_name: usuarios
    volumes:
      - ./backend/service_usuarios:/app
    ports:
      - "8001:8001"
    depends_on:
      - db_usuarios

  db_clientes:
    image: mysql:8.0
    container_name: db_clientes
    restart: always
    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - clientes_data:/var/lib/mysql

  clientes:
    build: ./backend/service_clientes
    container_name: clientes
    volumes:
      - ./backend/service_clientes:/app
    ports:
      - "8002:8002"
    depends_on:
      - db_clientes

  db_productos:
    image: mysql:8.0
    container_name: db_productos
    restart: always
    environment:
      MYSQL_DATABASE: productos_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - productos_data:/var/lib/mysql

  productos:
    build: ./backend/service_productos
    container_name: productos
    volumes:
      - ./backend/service_productos:/app
    ports:
      - "8003:8003"
    depends_on:
      - db_productos
    
  db_pedidos:
    image: mysql:8.0
    container_name: db_pedidos
    restart: always
    environment:
      MYSQL_DATABASE: pedidos_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3310:3306"
    volumes:
      - pedidos_data:/var/lib/mysql

  pedidos:
    build: ./backend/service_pedidos
    container_name: pedidos
    volumes:
      - ./backend/service_pedidos:/app
    ports:
      - "8004:8004"
    depends_on:
      - db_pedidos


volumes:
  usuarios_data:
  pedidos_data:
  clientes_data:
  productos_data:
