
services:

  db_usuarios:
    image: mysql:8.0
    container_name: db_usuarios
    restart: always
    environment:
      MYSQL_DATABASE: usuarios_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - usuarios_data:/var/lib/mysql

  usuarios:
    build: ./service_usuarios
    container_name: usuarios
    volumes:
      - ./service_usuarios:/app
    ports:
      - "8001:8001"
    depends_on:
      - db_usuarios


volumes:
  usuarios_data: