version: '3.8'

services:

  db_usuarios:
    image: mysql:8.0
    container_name: db_usuarios
    restart: always
    environment:
      MYSQL_DATABASE: usuarios_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - usuarios_data:/var/lib/mysql

  usuarios:
    build: ./service_usuarios
    container_name: usuarios
    volumes:
      - ./service_usuarios:/app
    ports:
      - "8001:8001"
    depends_on:
      - db_usuarios

  db_clientes:
    image: mysql:8.0
    container_name: db_clientes
    restart: always
    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3309:3306"
    volumes:
      - clientes_data:/var/lib/mysql

  clientes:
    build: ./service_clientes
    container_name: clientes
    volumes:
      - ./service_clientes:/app
    ports:
      - "8002:8002"
    depends_on:
      - db_clientes

  db_productos:
    image: mysql:8.0
    container_name: db_productos
    restart: always
    environment:
      MYSQL_DATABASE: productos_db
      MYSQL_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3310:3306"
    volumes:
      - productos_data:/var/lib/mysql

  productos:
    build: ./service_productos
    container_name: productos
    volumes:
      - ./service_productos:/app
    ports:
      - "8003:8002"
    depends_on:
      - db_productos

volumes:
  usuarios_data:
  clientes_data:
  productos_data:
