version: '3.8'

services:
  usuarios:
    build: ./service_usuarios
    ports:
      - "8001:8000"
    depends_on:
      - db_usuarios
  db_usuarios:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"

  productos:
    build: ./service_productos
    ports:
      - "8002:8000"
    depends_on:
      - db_productos
  db_productos:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productos_db
    ports:
      - "3307:3306"

  pedidos:
    build: ./service_pedidos
    ports:
      - "8003:8000"
    depends_on:
      - db_pedidos
  db_pedidos:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pedidos_db
    ports:
      - "3308:3306"
