# Generated by Django 5.2.1 on 2025-09-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoCobro',
            fields=[
                ('id', models.AutoField(db_column='id_metodo_cobro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_metodo_cobro', max_length=100)),
            ],
            options={
                'db_table': 'metodos_cobros',
            },
        ),
    ]
