# Generated by Django 5.2.1 on 2025-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(db_column='id_insumo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_insumo', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion_insumo', null=True)),
                ('unidad_medida', models.CharField(db_column='unidad_medida_insumo', max_length=20)),
                ('stock_actual', models.DecimalField(db_column='stock_actual_insumo', decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(db_column='costo_unitario_insumo', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
    ]
