# Generated by Django 5.2.1 on 2025-10-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_rol', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion_rol')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
