# Generated by Django 5.2.1 on 2025-09-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('productos', '0003_remove_producto_precio_por_bulto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(db_column='id_receta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_receta', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion_receta', null=True)),
                ('productos', models.ManyToManyField(db_table='receta_producto', related_name='recetas', to='productos.producto')),
            ],
            options={
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(db_column='cantidad_insumo', decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('receta', models.ForeignKey(db_column='id_receta', on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'receta_insumo',
                'unique_together': {('receta', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='insumos',
            field=models.ManyToManyField(related_name='recetas', through='recetas.RecetaInsumo', to='insumos.insumo'),
        ),
    ]
