# Generated by Django 5.2.1 on 2025-12-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='productos',
        ),
        migrations.CreateModel(
            name='RecetaSubReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(db_column='cantidad_sub_receta', decimal_places=2, max_digits=10)),
                ('receta_hija', models.ForeignKey(db_column='id_receta_hija', on_delete=django.db.models.deletion.CASCADE, related_name='recetasubreceta_componente', to='recetas.receta')),
                ('receta_padre', models.ForeignKey(db_column='id_receta_padre', on_delete=django.db.models.deletion.CASCADE, related_name='recetasubreceta_principal', to='recetas.receta')),
            ],
            options={
                'db_table': 'receta_sub_receta',
                'unique_together': {('receta_padre', 'receta_hija')},
            },
        ),
        migrations.AddField(
            model_name='receta',
            name='sub_recetas',
            field=models.ManyToManyField(related_name='es_ingrediente_de', through='recetas.RecetaSubReceta', to='recetas.receta'),
        ),
    ]
