# Generated by Django 5.2.1 on 2025-06-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosProductos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproductos',
            name='precio_unitario',
            field=models.DecimalField(db_column='precio_unitario', decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproductos',
            name='cantidad_producto',
            field=models.DecimalField(db_column='cantidad_producto', decimal_places=2, max_digits=6),
        ),
    ]
