# Generated by Django 5.2.1 on 2025-06-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosProductos', '0002_pedidoproductos_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidoproductos',
            table='pedidoProductos',
        ),
    ]
