# Generated by Django 5.2.1 on 2025-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosProductos', '0003_alter_pedidoproductos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproductos',
            name='aclaraciones',
            field=models.TextField(blank=True, db_column='aclaraciones'),
        ),
    ]
