# Generated by Django 4.2 on 2025-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre_producto', max_length=100)),
                ('descripcion', models.TextField(db_column='descripcion_producto')),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario_producto', decimal_places=2, max_digits=10)),
                ('precio_por_bulto', models.DecimalField(db_column='precio_por_bulto_producto', decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(db_column='disponible_producto', default=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
