# Generated by Django 5.2.1 on 2025-06-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
            preserve_default=False,
        ),
    ]
