# Generated by Django 5.2.1 on 2025-06-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_por_bulto',
        ),
    ]
