# Generated by Django 5.2.1 on 2025-12-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_precio_por_bulto'),
        ('recetas', '0002_remove_receta_productos_recetasubreceta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_receta',
            field=models.DecimalField(db_column='cantidad_consumo_receta', decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='receta',
            field=models.ForeignKey(blank=True, db_column='id_receta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_que_la_usan', to='recetas.receta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, db_column='stock_producto', default=0, null=True),
        ),
    ]
