# Generated by Django 5.2.1 on 2025-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('numero_pedido', models.IntegerField(db_column='numero_pedido')),
                ('fecha_pedido', models.DateField(db_column='fecha_pedido')),
                ('id_cliente', models.IntegerField(db_column='id_cliente')),
                ('para_hora', models.TimeField(db_column='para_hora', null=True)),
                ('entregado', models.BooleanField(db_column='entregado')),
                ('pagado', models.BooleanField(db_column='pagado')),
            ],
        ),
    ]
