# Generated by Django 5.2.1 on 2025-11-11 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('numero_pedido', models.IntegerField(db_column='numero_pedido')),
                ('fecha_pedido', models.DateTimeField(db_column='fecha_pedido', default=django.utils.timezone.now)),
                ('id_cliente', models.IntegerField(db_column='id_cliente')),
                ('cliente', models.CharField(db_column='cliente', default='Sin nombre', max_length=100)),
                ('para_hora', models.TimeField(db_column='para_hora', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('LISTO', 'LISTO'), ('ENTREGADO', 'ENTREGADO')], db_column='estado', default='PENDIENTE', max_length=20)),
                ('entregado', models.BooleanField(db_column='entregado')),
                ('avisado', models.BooleanField(db_column='avisado')),
                ('pagado', models.BooleanField(db_column='pagado')),
                ('total', models.DecimalField(db_column='total_pedido', decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
    ]
