# Generated by Django 5.2.1 on 2025-11-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='avisado',
            field=models.BooleanField(db_column='avisado', default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(db_column='entregado', default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(db_column='pagado', default=False),
        ),
    ]
