# Generated by Django 5.2.1 on 2025-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_avisado_alter_pedido_entregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
