# Generated by Django 5.2.1 on 2025-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], db_column='estado', default='PENDIENTE', max_length=20),
        ),
    ]
