# Generated by Django 5.2.1 on 2025-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('LISTO', 'LISTO'), ('ENTREGADO', 'ENTREGADO')], db_column='estado', default='PENDIENTE', max_length=20),
        ),
    ]
