# Generated by Django 5.2.1 on 2025-11-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_descuento_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='descuento_total',
        ),
    ]
