# Generated by Django 5.2.1 on 2025-07-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='avisado',
            field=models.BooleanField(db_column='avisado', default=False),
            preserve_default=False,
        ),
    ]
