# Generated by Django 5.2.1 on 2025-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_avisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(db_column='cliente', default='Sin nombre', max_length=100),
        ),
    ]
