# Generated by Django 5.2.1 on 2025-09-24 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(db_column='fecha_pedido', default=django.utils.timezone.now),
        ),
    ]