# Generated by Django 5.2.1 on 2025-10-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
    ]
