# Generated by Django 5.2.1 on 2025-11-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedido_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(db_column='total_pedido', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='avisado',
            field=models.BooleanField(db_column='avisado', default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(db_column='entregado', default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(db_column='pagado', default=False),
        ),
    ]
