# Generated by Django 5.2.1 on 2025-10-06 00:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(db_column='fecha_pedido', default=django.utils.timezone.now),
        ),
    ]
